### ISSUE TITLE
ScriptBlockPlus does not work under Paperspigot # 226 core

### ISSUE THREAD

**Issue by liaoxu2003** [yuttyann/ScriptBlockPlus#13] opened 2020-04-29 09:48 UTC
Error message in the background:

> org.bukkit.command.CommandException: Cannot execute command 'sbp' in plugin ScriptBlockPlus v1.8.5 - plugin is disabled.
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-226]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-226]
> at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:753) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-226]
> at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-226]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

What version of the core can successfully run ScriptBlockPlus？:-)

Thanks.

**Comment by yuttyann** [comment] 2020-05-02 19:51
Have you installed the prerequisite plugin [Vault](https://dev.bukkit.org/projects/vault)?

**Comment by liaoxu2003** [comment] 2020-05-04 17:01
Sure,i have installed Vault.(

**Comment by yuttyann** [comment] 2020-05-04 19:21
It couldn't be reproduced in my environment.
The plugin is not running due to some reason.

The solution is presented below.
1. Use Java8. (SBP is developed with Java 8.)
2. Try the latest v1.9.0.
3. Try the latest build of Paper.
4. Delete the plugins other than Vault and SBP, and check the plugin that is causing it.(However, this method assumes that it is caused by another plugin.)

**Comment by yuttyann** [comment] 2020-05-18 09:56
I have no reply, so I will close it.

**Closed as completed by yuttyann** 2020-05-18 09:56 UTC
Labels: 無効/Invalid
